"""Every new invoice and every recorded payment is emailed with its PDF (config/invoice.yaml `email`)."""
import dataclasses
import smtplib
from decimal import Decimal

import pytest
from fastapi.testclient import TestClient

from app.invoice import fmt, mailer
from app.main import create_app
from app.settings import get_settings

from .test_invoice_api import PASSCODE, invoice_body, k1_line


class FakeSMTP:
    sent: list = []
    logins: list = []
    fail = False

    def __init__(self, host, port, timeout):
        self.host, self.port = host, port

    def __enter__(self):
        if FakeSMTP.fail:
            raise smtplib.SMTPAuthenticationError(535, b"Username and Password not accepted")
        return self

    def __exit__(self, *exc):
        return False

    def login(self, user, password):
        FakeSMTP.logins.append((user, password))

    def send_message(self, msg):
        FakeSMTP.sent.append(msg)


@pytest.fixture(autouse=True)
def fake_smtp(monkeypatch):
    FakeSMTP.sent, FakeSMTP.logins, FakeSMTP.fail = [], [], False
    monkeypatch.setattr(mailer.smtplib, "SMTP_SSL", FakeSMTP)


def make_client(tmp_path, **settings_changes):
    settings_changes.setdefault("database_url", f"sqlite:///{(tmp_path / 'invoices.db').as_posix()}")
    settings = dataclasses.replace(get_settings(), staff_passcode=PASSCODE, secret_key="test-secret", **settings_changes)
    client = TestClient(create_app(settings))
    token = client.post("/api/staff/login", json={"passcode": PASSCODE}).json()["token"]
    return client, {"Authorization": f"Bearer {token}"}


def test_new_invoice_and_payment_are_emailed(tmp_path):
    client, auth = make_client(tmp_path, smtp_password="abcdefghijklmnop")
    r = client.post("/api/invoices", json=invoice_body([k1_line(client)]), headers=auth)
    assert r.status_code == 201
    [msg] = FakeSMTP.sent
    assert msg["To"] == msg["From"] == "printevrdesk@gmail.com"
    assert msg["Subject"] == "Invoice #19 – Sogat Jutti Store – by Mr. X"
    [pdf] = list(msg.iter_attachments())
    assert pdf.get_filename() == "Invoice_19_Sogat-Jutti-Store_Unpaid.pdf" and pdf.get_content() == r.content
    assert FakeSMTP.logins == [("printevrdesk@gmail.com", "abcdefghijklmnop")]

    r = client.post("/api/invoices/19/payments", json={"amount": "10000", "date": "2026-10-01", "mode": "upi"}, headers=auth)
    assert r.status_code == 200
    msg = FakeSMTP.sent[1]
    assert msg["Subject"] == "Payment recorded · Invoice #19 – Sogat Jutti Store – Part-paid"
    assert next(msg.iter_attachments()).get_content() == r.content
    assert "Generated by: Mr. X" in msg.get_body(("plain",)).get_content()
    assert "Amount received: Rs. 10000" in msg.get_body(("plain",)).get_content()


def bodies(msg):
    return msg.get_body(("plain",)).get_content(), msg.get_body(("html",)).get_content()


def test_email_lists_the_salesperson_and_the_sale(tmp_path):
    client, auth = make_client(tmp_path, smtp_password="abcdefghijklmnop")
    line = k1_line(client)
    subtotal = Decimal(str(line["quantity"])) * Decimal(line["unit_price"])
    pay = [{"amount": str(subtotal), "date": "2026-09-29", "mode": "upi", "note": None}]
    r = client.post("/api/invoices", json=invoice_body([line], print_mode="paid", payments=pay), headers=auth)
    assert r.status_code == 201
    [msg] = FakeSMTP.sent
    plain, html = bodies(msg)
    qty = f"{line['quantity']} {line['unit_label']}"
    rs = "Rs. " + fmt.amount(subtotal)
    for body in (plain, html):
        for expected in ("Mr. X", "Sogat Jutti Store", "19", "29 September 2026", line["title"], qty, rs,
                         "Paid in Full", "The invoice PDF is attached."):
            assert expected in body, expected
    assert "Generated by: Mr. X" in plain
    assert f"Amount received: {rs}" in plain and "Amount pending: Rs. 0" in plain
    assert "Payment status: Paid in Full" in plain
    [pdf] = list(msg.iter_attachments())
    assert pdf.get_content_type() == "application/pdf" and pdf.get_content() == r.content


def test_unpaid_email_shows_everything_pending(tmp_path):
    client, auth = make_client(tmp_path, smtp_password="abcdefghijklmnop")
    line = k1_line(client)
    assert client.post("/api/invoices", json=invoice_body([line]), headers=auth).status_code == 201
    plain, _ = bodies(FakeSMTP.sent[0])
    subtotal = Decimal(str(line["quantity"])) * Decimal(line["unit_price"])
    assert "Payment status: Unpaid" in plain and "Amount received: Rs. 0" in plain
    assert f"Amount pending: Rs. {fmt.amount(subtotal)}" in plain


def test_typed_text_is_escaped_in_the_html(tmp_path):
    client, auth = make_client(tmp_path, smtp_password="abcdefghijklmnop")
    body = invoice_body([k1_line(client)], salesperson='<b onclick="x">Mr. & X</b>')
    body["customer"]["business_name"] = "<script>alert(1)</script> Co"
    assert client.post("/api/invoices", json=body, headers=auth).status_code == 201
    [msg] = FakeSMTP.sent
    _, html = bodies(msg)
    assert "<script>" not in html and "<b onclick" not in html
    assert "&lt;b onclick=&quot;x&quot;&gt;Mr. &amp; X&lt;/b&gt;" in html
    assert "&lt;script&gt;alert(1)&lt;/script&gt; Co" in html
    assert "\n" not in msg["Subject"] and 'by <b onclick="x">Mr. & X</b>' in msg["Subject"]


def test_unsaved_invoices_are_emailed_with_the_salesperson(tmp_path):
    client, auth = make_client(tmp_path, smtp_password="abcdefghijklmnop", database_url=None)
    r = client.post("/api/invoices", json=invoice_body([k1_line(client)], bill_no=41), headers=auth)
    assert r.status_code == 201
    [msg] = FakeSMTP.sent
    assert msg["Subject"] == "Invoice #41 – Sogat Jutti Store – by Mr. X"
    assert "Generated by: Mr. X" in bodies(msg)[0]


def test_a_mail_failure_never_stops_the_invoice(tmp_path):
    client, auth = make_client(tmp_path, smtp_password="wrong")
    FakeSMTP.fail = True
    r = client.post("/api/invoices", json=invoice_body([k1_line(client)]), headers=auth)
    assert r.status_code == 201 and r.content.startswith(b"%PDF")
    assert client.get("/api/invoices/19", headers=auth).status_code == 200


def test_no_password_no_email(tmp_path):
    client, auth = make_client(tmp_path, smtp_password=None)
    assert client.post("/api/invoices", json=invoice_body([k1_line(client)]), headers=auth).status_code == 201
    assert FakeSMTP.sent == []
